# name: reuse workflow example
# on: 
#   workflow_call:
#     inputs:
#       artifact-name:
#         description: name of the artifact
#         required: false
#         default: dist
#         type: string
#     # secrets:
#     #   password:
#     #     required: true
#     outputs:
#       result:
#         description: your result name
#         value: ${{ jobs.deploy.outputs.outcome }}
# jobs:
#   deploy:
#     outputs:
#       outcome: ${{ steps.set-result.outputs.step-result }}
#     runs-on: ubuntu-slim
#     steps:
#       - name: get artifact
#         uses: actions/download-artifact@v5
#         with:
#           name: ${{ inputs.artifact-name }}
#       - name: list artifact name
#         run: ls
#       - name: set the outputs
#         id: set-result
#         run: echo "step-result=success" >> $GITHUB_OUTPUT
        
############################################

name: Reuse workflow example
on: 
  workflow_call:  #1task) workflow_call is used when you want to call a workflow from another workflow
    inputs:       #2task)
      artifact-name:
        description: name of the artifact
        required: false
        default: dist
        type: string
jobs:
  deploy2:
    runs-on: ubuntu-slim
    steps:
      - name: get artifact         #2task)
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}
      - name: list artifact name    #2task)
        run: ls
      - name: output data                          # 1task)
        run: echo "hello from the reusable workflow"